// iPlan (GTsemasa) land use lookup for Solar SiteIQ.
//
// Reads a pre-rasterised grid file generated by scripts/build-iplan-grid.mjs.
// Each entry maps a 1 km cell centre key ("lat_lng") to a LandUseClass string.
// O(1) lookup — no ring traversal needed.
//
// File: public/data/iplan-grid.json
//   {version:2, grid:{[key:string]:string}, gridGapFilled:{[key:string]:string}}
// `grid` holds cells iPlan itself directly classified (real cadastral sample
// data) — highest-confidence signal, consulted early in grid1km.ts's priority
// chain. `gridGapFilled` holds cells with zero direct iPlan coverage that were
// spatially inferred from nearby classified cells (see build-iplan-grid.mjs) —
// a real but weaker signal, since it's an inference, not an observation. It
// must never outrank OSM: e.g. Sungai Petani's town core has no direct iPlan
// data and sits inside the vast MADA rice-growing region, so gap-fill
// confidently (and wrongly) infers 'paddy' there — only consulting it AFTER
// OSM lets OSM's real place=city/landuse=residential data win instead.
//
// Cache: IndexedDB (key "iplan-grid-v10", 30-day TTL)

import type { LandUseClass, RiskLevel } from '../types';
import { idbGet, idbSet } from './idbCache';

export const IPLAN_CACHE_KEY = 'iplan-grid-v13'; // v13 = split livestock + aquaculture out of mixed_agri
const CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000;

interface GridFile {
  version: number;
  grid: Record<string, string>;
  gridGapFilled?: Record<string, string>;
}

interface IplanCacheData {
  grid: Record<string, string>;
  gridGapFilled: Record<string, string>;
}

let _grid: Record<string, string> | null = null;
let _gridGapFilled: Record<string, string> | null = null;

// paddy, river and aquaculture (low-lying water-adjacent ponds) have elevated flood risk
const FLOOD_RISK_HIGH: ReadonlySet<string> = new Set(['paddy', 'river', 'aquaculture']);
// forest from iPlan is always protected reserve forest (plantation/community wood = 'idle_agri')
// river is never developable — same treatment as protected land for capacity purposes
const PROTECTED_CLASSES: ReadonlySet<string> = new Set(['forest', 'river']);

// ── Loading ───────────────────────────────────────────────────────────────────

let _loadPromise: Promise<void> | null = null;

export function ensureIplanLanduseLoaded(_signal?: AbortSignal): Promise<void> {
  if (_loadPromise) return _loadPromise;
  _loadPromise = (async () => {
    // Check IndexedDB cache first (avoids refetch on subsequent page loads)
    const cached = await idbGet<IplanCacheData>(IPLAN_CACHE_KEY);
    if (cached && (Date.now() - cached.fetchedAt) < CACHE_TTL_MS) {
      _grid = cached.data.grid;
      _gridGapFilled = cached.data.gridGapFilled;
      return;
    }

    // Fetch static pre-rasterised file (committed to repo, served from CDN)
    try {
      const res = await fetch('/data/iplan-grid.json');
      if (!res.ok) {
        console.info('iPlan: no grid file found — land use falls back to OSM/WorldCover. Run scripts/fetch-iplan-raw.mjs + build-iplan-grid.mjs to generate it.');
        _grid = {};
        _gridGapFilled = {};
        return;
      }
      const data = (await res.json()) as GridFile;
      if (data?.version === 2 && data.grid) {
        _grid = data.grid;
        _gridGapFilled = data.gridGapFilled ?? {};
        const cacheData: IplanCacheData = { grid: _grid, gridGapFilled: _gridGapFilled };
        await idbSet(IPLAN_CACHE_KEY, cacheData);
        console.info(`iPlan: loaded ${Object.keys(data.grid).length} direct + ${Object.keys(_gridGapFilled).length} gap-filled grid cells`);
      } else {
        _grid = {};
        _gridGapFilled = {};
      }
    } catch {
      _grid = {};
      _gridGapFilled = {};
    }
  })().catch((err) => {
    _loadPromise = null;
    if ((err as Error).name !== 'AbortError') throw err;
  });
  return _loadPromise;
}

// ── Lookup ────────────────────────────────────────────────────────────────────

function classify(lu: string | undefined): { landUse: LandUseClass; floodRisk: RiskLevel; isProtected: boolean } | null {
  if (!lu) return null;
  return {
    landUse:     lu as LandUseClass,
    floodRisk:   FLOOD_RISK_HIGH.has(lu) ? 'medium' : 'low',
    isProtected: PROTECTED_CLASSES.has(lu),
  };
}

/**
 * Return the DIRECT iPlan land use classification for a 1 km cell centre —
 * real cadastral sample data only, not spatially inferred. `lat`/`lng` must be
 * the exact centre coords as computed in grid1km.ts (swLat + 0.0045, toFixed(4)).
 * Returns null if the file hasn't loaded, or if the cell has no direct iPlan data.
 */
export function getIplanLanduseAt(
  lat: number,
  lng: number,
): { landUse: LandUseClass; floodRisk: RiskLevel; isProtected: boolean } | null {
  if (!_grid) return null;
  return classify(_grid[`${lat.toFixed(4)}_${lng.toFixed(4)}`]);
}

/**
 * Return the GAP-FILLED (spatially inferred from nearby classified cells)
 * classification for a 1 km cell centre. Only meaningful for cells where
 * getIplanLanduseAt() returns null. Deliberately a separate, lower-confidence
 * lookup — callers should consult this only after OSM has also had a chance
 * to answer, since an inference must never outrank a real observation.
 */
export function getIplanGapFillLanduseAt(
  lat: number,
  lng: number,
): { landUse: LandUseClass; floodRisk: RiskLevel; isProtected: boolean } | null {
  if (!_gridGapFilled) return null;
  return classify(_gridGapFilled[`${lat.toFixed(4)}_${lng.toFixed(4)}`]);
}
