// iPlan (GTsemasa) land use lookup for Solar SiteIQ.
//
// Reads a pre-rasterised grid file generated by scripts/download-iplan.mjs.
// Each entry maps a 1 km cell centre key ("lat_lng") to a LandUseClass string.
// O(1) lookup — no ring traversal needed.
//
// File: public/data/iplan-grid.json  {version:2, grid:{[key:string]:string}}
// Cache: IndexedDB (key "iplan-grid-v8", 30-day TTL)

import type { LandUseClass, RiskLevel } from '../types';
import { idbGet, idbSet } from './idbCache';

const CACHE_KEY    = 'iplan-grid-v8'; // v8 = spatial gap-fill for cells with no direct iPlan coverage (was defaulting forested hill country to idle_agri)
const CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000;

interface GridFile {
  version: number;
  grid: Record<string, string>;
}

let _grid: Record<string, string> | null = null;

// paddy and river cells have elevated flood risk in Malaysia
const FLOOD_RISK_HIGH: ReadonlySet<string> = new Set(['paddy', 'river']);
// forest from iPlan is always protected reserve forest (plantation/community wood = 'idle_agri')
// river is never developable — same treatment as protected land for capacity purposes
const PROTECTED_CLASSES: ReadonlySet<string> = new Set(['forest', 'river']);

// ── Loading ───────────────────────────────────────────────────────────────────

let _loadPromise: Promise<void> | null = null;

export function ensureIplanLanduseLoaded(_signal?: AbortSignal): Promise<void> {
  if (_loadPromise) return _loadPromise;
  _loadPromise = (async () => {
    // Check IndexedDB cache first (avoids refetch on subsequent page loads)
    const cached = await idbGet<Record<string, string>>(CACHE_KEY);
    if (cached && (Date.now() - cached.fetchedAt) < CACHE_TTL_MS) {
      _grid = cached.data;
      return;
    }

    // Fetch static pre-rasterised file (committed to repo, served from CDN)
    try {
      const res = await fetch('/data/iplan-grid.json');
      if (!res.ok) {
        console.info('iPlan: no grid file found — land use falls back to OSM/WorldCover. Run scripts/download-iplan.mjs to generate it.');
        _grid = {};
        return;
      }
      const data = (await res.json()) as GridFile;
      if (data?.version === 2 && data.grid) {
        _grid = data.grid;
        await idbSet(CACHE_KEY, data.grid);
        console.info(`iPlan: loaded ${Object.keys(data.grid).length} grid cells`);
      } else {
        _grid = {};
      }
    } catch {
      _grid = {};
    }
  })().catch((err) => {
    _loadPromise = null;
    if ((err as Error).name !== 'AbortError') throw err;
  });
  return _loadPromise;
}

// ── Lookup ────────────────────────────────────────────────────────────────────

/**
 * Return the iPlan land use classification for a 1 km cell centre.
 * `lat` and `lng` must be the exact centre coords as computed in grid1km.ts
 * (i.e. swLat + 0.0045 rounded to 4 dp — toFixed(4)).
 * Returns null if the file hasn't loaded, or if the cell has no iPlan data.
 */
export function getIplanLanduseAt(
  lat: number,
  lng: number,
): { landUse: LandUseClass; floodRisk: RiskLevel; isProtected: boolean } | null {
  if (!_grid) return null;
  const key = `${lat.toFixed(4)}_${lng.toFixed(4)}`;
  const lu = _grid[key];
  if (!lu) return null;
  return {
    landUse:     lu as LandUseClass,
    floodRisk:   FLOOD_RISK_HIGH.has(lu) ? 'medium' : 'low',
    isProtected: PROTECTED_CLASSES.has(lu),
  };
}
