// PVGIS solar yield data for Solar SiteIQ.
//
// Loads a pre-downloaded 0.05° static grid (public/data/pvgis-grid.json)
// generated by scripts/download-pvgis.mjs.  Bilinearly interpolates yield
// at any 1 km cell centre.  No DuckDB or runtime API call needed.
//
// Cache: IndexedDB (key "pvgis-grid-v2", 90-day TTL).  On first load the file
// is fetched from CDN and stored in IDB — subsequent page loads are instant.
//
// Fallback: if the static file is missing, interpolatePvgis returns hiY=0 so
// grid1km.ts falls through to estimateGHI() from the ghi.ts zone table.
//
// Run  node scripts/download-pvgis.mjs  once to regenerate the file.

// Ground-mounted solar density — 1 MWp/ha = 100,000 kWp/km² (Malaysian LSS standard)
export const SOLAR_DENSITY_KWP_PER_KM2 = 100_000;

// Usable fraction by land use type.
// Ground-mount: land is cleared when converted to solar → full density regardless of prior crop.
// FPV / rooftop: physical area constraints apply.
export const USABLE_FRACTION: Partial<Record<string, number>> = {
  idle_agri:  1.00,
  rubber:     1.00,
  mixed_agri: 1.00,
  oil_palm:   1.00,
  paddy:      1.00,
  water:      0.30,  // FPV: 30% of still-water body usable (lakes, reservoirs, ponds)
  industrial: 0.50,  // ~30% rooftop + ~20% carpark of gross area
  commercial: 0.40,  // ~25% rooftop + ~15% carpark of gross area
  urban:      0.15,  // residential: smaller pitched roofs
  kampung:    0.20,  // rural village: larger house plots with garden/yard space
  infrastructure: 0.10, // occupied utility facility — limited spare land/carport potential
  forest:     0.00,
  river:      0.00,  // flowing water — not developable
};

export interface PvgisResult {
  eY: number;       // kWh/kWp/year (specific yield)
  perfRatio: number;
  hiY: number;      // irradiation on inclined plane, kWh/m²/year (0 = no data)
}

// ── Static grid ───────────────────────────────────────────────────────────────

import { idbGet, idbSet } from './idbCache';

const PVGIS_CACHE_KEY    = 'pvgis-grid-v3'; // v3 = 0.05° grid (2179 pts), regenerated 2026-06
const PVGIS_CACHE_TTL_MS = 90 * 24 * 60 * 60 * 1000; // 90 days — irradiance data is very stable

interface PvgisPoint    { lat: number; lng: number; eY: number; hiY: number; pr: number }
interface PvgisGridFile { version: number; step: number; bbox: object; points: PvgisPoint[] }

let _pvgisGrid: Map<string, PvgisResult> | null = null;
let _pvgisStep = 0.05;

function gridKey(lat: number, lng: number, step: number): string {
  const scale = Math.round(1 / step * 10);
  return `${Math.round(lat * scale)}_${Math.round(lng * scale)}`;
}

function parsePoints(points: PvgisPoint[], step: number): Map<string, PvgisResult> {
  const map = new Map<string, PvgisResult>();
  for (const p of points) {
    map.set(gridKey(p.lat, p.lng, step), { eY: p.eY, perfRatio: p.pr, hiY: p.hiY });
  }
  return map;
}

async function loadStaticGrid(): Promise<void> {
  // L1: IndexedDB — instant for returning visitors
  const cached = await idbGet<{ points: PvgisPoint[]; step: number }>(PVGIS_CACHE_KEY);
  if (cached && (Date.now() - cached.fetchedAt) < PVGIS_CACHE_TTL_MS) {
    _pvgisStep = cached.data.step ?? 0.05;
    _pvgisGrid = parsePoints(cached.data.points, _pvgisStep);
    console.info(`PVGIS: ${_pvgisGrid.size} points from IndexedDB (${_pvgisStep}° grid)`);
    return;
  }

  // L2: CDN fetch — parse and cache for next session
  try {
    const res = await fetch('/data/pvgis-grid.json');
    if (!res.ok) {
      console.info('PVGIS: no static grid found — using estimateGHI() fallback. Run scripts/download-pvgis.mjs to generate it.');
      _pvgisGrid = new Map();
      return;
    }
    const data = (await res.json()) as PvgisGridFile;
    if (!data?.points?.length) { _pvgisGrid = new Map(); return; }

    _pvgisStep = data.step ?? 0.05;
    _pvgisGrid = parsePoints(data.points, _pvgisStep);
    // Save parsed points array (not the Map) — IDB serialises plain objects
    await idbSet(PVGIS_CACHE_KEY, { points: data.points, step: _pvgisStep });
    console.info(`PVGIS: loaded ${_pvgisGrid.size} points at ${_pvgisStep}° from CDN, cached to IDB`);
  } catch {
    _pvgisGrid = new Map();
  }
}

// ── Public loading API ────────────────────────────────────────────────────────

let _loadPromise: Promise<void> | null = null;

export async function ensurePvgisGrid(): Promise<void> {
  if (_pvgisGrid !== null) return;
  if (_loadPromise) return _loadPromise;
  _loadPromise = loadStaticGrid();
  return _loadPromise;
}

// ── Bilinear interpolation ────────────────────────────────────────────────────

const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

/**
 * Bilinearly interpolate PVGIS yield at an arbitrary 1 km cell centre.
 * Returns hiY=0 when no data — grid1km.ts uses that as the signal to call estimateGHI().
 */
export function interpolatePvgis(lat: number, lng: number): PvgisResult {
  if (!_pvgisGrid || _pvgisGrid.size === 0) {
    return { eY: 1_420, perfRatio: 0.86, hiY: 0 }; // hiY=0 → estimateGHI fallback
  }

  const step = _pvgisStep;
  const la0 = Math.floor(lat / step) * step;
  const la1 = la0 + step;
  const lo0 = Math.floor(lng / step) * step;
  const lo1 = lo0 + step;

  const q00 = _pvgisGrid.get(gridKey(la0, lo0, step));
  const q10 = _pvgisGrid.get(gridKey(la1, lo0, step));
  const q01 = _pvgisGrid.get(gridKey(la0, lo1, step));
  const q11 = _pvgisGrid.get(gridKey(la1, lo1, step));

  // All four corners needed for bilinear; fall back to nearest available
  if (!q00 || !q10 || !q01 || !q11) {
    const fallback = q00 ?? q10 ?? q01 ?? q11;
    return fallback ?? { eY: 1_420, perfRatio: 0.86, hiY: 0 };
  }

  const tx = (lng - lo0) / step;
  const ty = (lat - la0) / step;

  return {
    eY:        lerp(lerp(q00.eY,        q01.eY,        tx), lerp(q10.eY,        q11.eY,        tx), ty),
    perfRatio: lerp(lerp(q00.perfRatio, q01.perfRatio, tx), lerp(q10.perfRatio, q11.perfRatio, tx), ty),
    hiY:       lerp(lerp(q00.hiY,       q01.hiY,       tx), lerp(q10.hiY,       q11.hiY,       tx), ty),
  };
}

// ── Capacity calculation ──────────────────────────────────────────────────────

/** Calculate installed capacity and annual yield for a 1 km² cell. */
export function calcCapacity(
  landUse: string,
  isProtected: boolean,
  pvgisEy: number,
): { capacityKWp: number; annualYieldMWh: number } {
  if (isProtected || landUse === 'forest' || landUse === 'river') return { capacityKWp: 0, annualYieldMWh: 0 };
  const fraction = USABLE_FRACTION[landUse] ?? 0.30;
  const capacityKWp    = Math.round(SOLAR_DENSITY_KWP_PER_KM2 * fraction);
  const annualYieldMWh = Math.round(capacityKWp * pvgisEy / 1000);
  return { capacityKWp, annualYieldMWh };
}
