// PVGIS solar yield data for Solar SiteIQ.
//
// Loads a pre-downloaded 0.1° static grid (public/data/pvgis-grid.json)
// generated by scripts/download-pvgis.mjs.  Bilinearly interpolates yield
// at any 1 km cell centre.  No DuckDB or runtime API call needed.
//
// Fallback: if the static file is missing (first run / local dev without it),
// interpolatePvgis returns hiY=0 so grid1km.ts falls through to estimateGHI()
// which provides regional variation from the ghi.ts zone table.
//
// Run  node scripts/download-pvgis.mjs  once to generate the file.

// Ground-mounted solar density — 1 MWp/ha = 100,000 kWp/km² (Malaysian LSS standard)
export const SOLAR_DENSITY_KWP_PER_KM2 = 100_000;

// Usable fraction by land use type.
// Ground-mount: land is cleared when converted to solar → full density regardless of prior crop.
// FPV / rooftop: physical area constraints apply.
export const USABLE_FRACTION: Partial<Record<string, number>> = {
  idle_agri:  1.00,
  rubber:     1.00,
  mixed_agri: 1.00,
  oil_palm:   1.00,
  paddy:      1.00,
  water:      0.70,  // FPV: ~70% of reservoir surface usable
  industrial: 0.50,  // ~30% rooftop + ~20% carpark of gross area
  commercial: 0.40,  // ~25% rooftop + ~15% carpark of gross area
  urban:      0.15,  // residential: smaller pitched roofs
  forest:     0.00,
};

export interface PvgisResult {
  eY: number;       // kWh/kWp/year (specific yield)
  perfRatio: number;
  hiY: number;      // irradiation on inclined plane, kWh/m²/year (0 = no data)
}

// ── Static grid ───────────────────────────────────────────────────────────────

interface PvgisPoint { lat: number; lng: number; eY: number; hiY: number; pr: number }
interface PvgisGridFile { version: number; step: number; bbox: object; points: PvgisPoint[] }

let _pvgisGrid: Map<string, PvgisResult> | null = null;
let _pvgisStep = 0.1;

function gridKey(lat: number, lng: number, step: number): string {
  const scale = Math.round(1 / step * 10);
  return `${Math.round(lat * scale)}_${Math.round(lng * scale)}`;
}

async function loadStaticGrid(): Promise<void> {
  try {
    const res = await fetch('/data/pvgis-grid.json');
    if (!res.ok) {
      console.info('PVGIS: no static grid found — using estimateGHI() fallback. Run scripts/download-pvgis.mjs to generate it.');
      _pvgisGrid = new Map();
      return;
    }
    const data = (await res.json()) as PvgisGridFile;
    if (!data?.points?.length) { _pvgisGrid = new Map(); return; }

    _pvgisStep = data.step ?? 0.1;
    const map = new Map<string, PvgisResult>();
    for (const p of data.points) {
      map.set(gridKey(p.lat, p.lng, _pvgisStep), {
        eY: p.eY, perfRatio: p.pr, hiY: p.hiY,
      });
    }
    _pvgisGrid = map;
    console.info(`PVGIS: loaded ${map.size} grid points at ${_pvgisStep}° resolution`);
  } catch {
    _pvgisGrid = new Map();
  }
}

// ── Public loading API ────────────────────────────────────────────────────────

let _loadPromise: Promise<void> | null = null;

export async function ensurePvgisGrid(): Promise<void> {
  if (_pvgisGrid !== null) return;
  if (_loadPromise) return _loadPromise;
  _loadPromise = loadStaticGrid();
  return _loadPromise;
}

// ── Bilinear interpolation ────────────────────────────────────────────────────

const lerp = (a: number, b: number, t: number) => a + (b - a) * t;

/**
 * Bilinearly interpolate PVGIS yield at an arbitrary 1 km cell centre.
 * Returns hiY=0 when no data — grid1km.ts uses that as the signal to call estimateGHI().
 */
export function interpolatePvgis(lat: number, lng: number): PvgisResult {
  if (!_pvgisGrid || _pvgisGrid.size === 0) {
    return { eY: 1_420, perfRatio: 0.86, hiY: 0 }; // hiY=0 → estimateGHI fallback
  }

  const step = _pvgisStep;
  const la0 = Math.floor(lat / step) * step;
  const la1 = la0 + step;
  const lo0 = Math.floor(lng / step) * step;
  const lo1 = lo0 + step;

  const q00 = _pvgisGrid.get(gridKey(la0, lo0, step));
  const q10 = _pvgisGrid.get(gridKey(la1, lo0, step));
  const q01 = _pvgisGrid.get(gridKey(la0, lo1, step));
  const q11 = _pvgisGrid.get(gridKey(la1, lo1, step));

  // All four corners needed for bilinear; fall back to nearest available
  if (!q00 || !q10 || !q01 || !q11) {
    const fallback = q00 ?? q10 ?? q01 ?? q11;
    return fallback ?? { eY: 1_420, perfRatio: 0.86, hiY: 0 };
  }

  const tx = (lng - lo0) / step;
  const ty = (lat - la0) / step;

  return {
    eY:        lerp(lerp(q00.eY,        q01.eY,        tx), lerp(q10.eY,        q11.eY,        tx), ty),
    perfRatio: lerp(lerp(q00.perfRatio, q01.perfRatio, tx), lerp(q10.perfRatio, q11.perfRatio, tx), ty),
    hiY:       lerp(lerp(q00.hiY,       q01.hiY,       tx), lerp(q10.hiY,       q11.hiY,       tx), ty),
  };
}

// ── Capacity calculation ──────────────────────────────────────────────────────

/** Calculate installed capacity and annual yield for a 1 km² cell. */
export function calcCapacity(
  landUse: string,
  isProtected: boolean,
  pvgisEy: number,
): { capacityKWp: number; annualYieldMWh: number } {
  if (isProtected || landUse === 'forest') return { capacityKWp: 0, annualYieldMWh: 0 };
  const fraction = USABLE_FRACTION[landUse] ?? 0.30;
  const capacityKWp    = Math.round(SOLAR_DENSITY_KWP_PER_KM2 * fraction);
  const annualYieldMWh = Math.round(capacityKWp * pvgisEy / 1000);
  return { capacityKWp, annualYieldMWh };
}
