// Road distance grid for Solar SiteIQ.
//
// Loads a pre-computed per-cell static file (public/data/road-dist-grid.json)
// generated by scripts/build-road-grid.mjs.  Provides O(1) lookup of distance
// to the nearest trunk/primary/secondary/tertiary road for each 1 km grid cell.
//
// Cache: IndexedDB (key "road-dist-v1", 30-day TTL).  On first load the file is
// fetched from CDN and stored in IDB — subsequent page loads are instant.
//
// Fallback: if the file is missing, returns null → grid1km.ts uses the
// hand-crafted ROAD_POLYLINES estimate instead.

import { idbGet, idbSet } from './idbCache';

const ROAD_CACHE_KEY    = 'road-dist-v1';
const ROAD_CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

interface RoadDistFile {
  version: number;
  bbox:    { south: number; north: number; west: number; east: number };
  step:    number;
  grid:    Record<string, number>;
}

let _grid: Record<string, number> | null = null;
let _loadPromise: Promise<void> | null = null;

async function loadRoadDistGrid(): Promise<void> {
  // L1: IndexedDB — instant for returning visitors
  const cached = await idbGet<Record<string, number>>(ROAD_CACHE_KEY);
  if (cached && (Date.now() - cached.fetchedAt) < ROAD_CACHE_TTL_MS) {
    _grid = cached.data;
    console.info(`Road dist: ${Object.keys(_grid).length.toLocaleString()} cells from IndexedDB`);
    return;
  }

  // L2: CDN fetch — parse and cache for next session
  try {
    const res = await fetch('/data/road-dist-grid.json');
    if (!res.ok) {
      console.info('Road dist: no static grid found — falling back to polyline estimates. Run scripts/build-road-grid.mjs to generate it.');
      _grid = {};
      return;
    }
    const data = (await res.json()) as RoadDistFile;
    if (!data?.grid) { _grid = {}; return; }

    _grid = data.grid;
    await idbSet(ROAD_CACHE_KEY, _grid);
    const vals = Object.values(_grid);
    console.info(`Road dist: loaded ${vals.length.toLocaleString()} cells from CDN, dist ${Math.min(...vals).toFixed(1)}–${Math.max(...vals).toFixed(1)} km, cached to IDB`);
  } catch {
    _grid = {};
  }
}

export async function ensureRoadDistGrid(): Promise<void> {
  if (_grid !== null) return;
  if (_loadPromise) return _loadPromise;
  _loadPromise = loadRoadDistGrid();
  return _loadPromise;
}

/**
 * Distance in km to nearest trunk/primary/secondary/tertiary road at a 1 km cell centre.
 * Returns null when the static grid is unavailable (triggers polyline fallback in grid1km.ts).
 *
 * Key matches the cell-centre format from grid1km.ts:
 *   cLat = +(swLat + GRID_STEP / 2).toFixed(4)
 */
export function getRoadDistAt(lat: number, lng: number): number | null {
  if (!_grid) return null;
  const key = `${lat.toFixed(4)}_${lng.toFixed(4)}`;
  const v = _grid[key];
  return v !== undefined ? v : null;
}
